
version: 2
updates:
    - package-ecosystem: "composer"
      directory: "/"
      reviewers:
          - tomas-kulhanek
      schedule:
          interval: "daily"
          day: monday
      commit-message:
          prefix: "chore"
      open-pull-requests-limit: 10
      groups:
          symfony:
              patterns:
                  - "symfony/*"
                  - "twig/*"
                  - "doctrine/*"
          scheb:
              patterns:
                  - "scheb/*"

    - package-ecosystem: github-actions
      directory: "/"
      assignees:
          - tomas-kulhanek
      reviewers:
          - tomas-kulhanek
      schedule:
          interval: weekly
          day: monday
